// Bundles the landing page's client JS and emits it as a TS module, so the
// server build inlines a string it can see rather than depending on static
// asset serving. The deploy is a single file; there is nowhere to put a .js.
//
// Run before any server build. `pnpm build:server` and `build:api` both depend
// on it, so a stale or missing bundle cannot ship.
import { build } from "esbuild";
import { writeFileSync, mkdirSync } from "node:fs";
import { gzipSync } from "node:zlib";

mkdirSync("src/generated", { recursive: true });

const result = await build({
  entryPoints: ["src/client/hero.ts"],
  bundle: true,
  minify: true,
  format: "iife",
  target: "es2019",
  platform: "browser",
  legalComments: "none",
  write: false,
});

const code = result.outputFiles[0].text;
const gz = gzipSync(Buffer.from(code)).length;

writeFileSync(
  "src/generated/hero-bundle.ts",
  "// GENERATED by scripts/build-client.mjs. Do not edit.\n" +
    "/* eslint-disable */\n" +
    `export const HERO_BUNDLE = ${JSON.stringify(code)};\n` +
    `export const HERO_BUNDLE_GZIP_BYTES = ${gz};\n`,
);

console.log(
  `  client bundle: ${(code.length / 1024).toFixed(1)} KB raw, ` +
    `${(gz / 1024).toFixed(1)} KB gzipped`,
);
