// Turns binary assets into a plain TypeScript module.
//
// Importing .woff2 directly only works under esbuild's base64 loader, which
// meant `pnpm dev`, `pnpm start` and the test runner all failed with
// ERR_UNKNOWN_FILE_EXTENSION. Emitting ordinary TypeScript instead works
// everywhere with no loader configuration, the same way the client bundle does.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
mkdirSync(join(root, "src/generated"), { recursive: true });

const FONTS = {
  SERIF_B64: "instrument-serif-400.woff2",
  SANS_B64: "geist-var.woff2",
  MONO_B64: "geist-mono-var.woff2",
};

let out =
  "// GENERATED by scripts/build-assets.mjs. Do not edit.\n" +
  "// Latin woff2 subsets, base64. Sources live in src/assets/.\n";
let total = 0;
for (const [name, file] of Object.entries(FONTS)) {
  const buf = readFileSync(join(root, "src/assets", file));
  total += buf.length;
  out += `export const ${name} = ${JSON.stringify(buf.toString("base64"))};\n`;
  console.log(`  ${file.padEnd(28)} ${(buf.length / 1024).toFixed(1)} KB`);
}
writeFileSync(join(root, "src/generated/fonts-data.ts"), out);
console.log(`  fonts total: ${(total / 1024).toFixed(1)} KB on the wire`);

// The listing avatar, served from our own origin so the marketplace has a stable
// URL to fetch. `agent update --picture` takes a URL, not an upload, and a link
// to someone else's host would put our listing image at their uptime's mercy.
const avatar = readFileSync(join(root, "src/assets/avatar.png"));
writeFileSync(
  join(root, "src/generated/avatar-data.ts"),
  "// GENERATED by scripts/build-assets.mjs. Do not edit.\n" +
    "// Listing avatar PNG, base64. Source is src/assets/avatar.png.\n" +
    `export const AVATAR_B64 = ${JSON.stringify(avatar.toString("base64"))};\n`,
);
console.log(`  avatar.png${" ".repeat(18)} ${(avatar.length / 1024).toFixed(1)} KB`);
